export { default as Wish } from './Wish/Wish';
export { default as Team } from './Team/Team';
export { default as Home } from './Home/Home';
export { default as Individual } from './Individual/Individual';
export { default as Church } from './Church/Church';
export { default as Business } from './Business/Business';
export { default as WDonate } from './WDonate/WDonate';
export { default as Contact } from './Contact/Contact';
export { default as Donate } from './Donate/Donate';
